[package]
name = "std_deviation"
version = "0.1.0"
authors = ["wu2305"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
